### ISSUE TITLE
Clean up file structure to allow for additional integrations. . .

### ISSUE THREAD

**Issue by MickeyKay** [MIGHTYminnow/mm-components#20]
Right now we do everything for a given component in a single file. Let's separate this out so that we can integrate other page-builders/tools as time goes on - something like this:
- /button
  - shortcodes.php
  - visual-composer.php
  - shortcake.php (when ready)

**Comment by BraadMartin** [comment]
+1. Each component in its own folder with one shared CSS file and JS file for now (ideally we'd use Grunt or something similar to produce built CSS and JS files from the individual component files eventually). I'd even support creating a CSS and JS file now (as needed) for each component and then manually keeping the master CSS and JS files up to date as we further develop each component, but we can split these out later to avoid maintaining two copies now also.

**Comment by BraadMartin** [comment]
One last point, would it be better to have /button and the files inside be button-shortcode.php, button-vc.php, etc. rather than use generic names for each component file? I know they are inside of a named folder, but are there any situations where we would want unique filenames? I'm fine either way, just a thought.
